package cctl

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"time"
)

// This file implements the remote-claude → cmux notification bridge.
//
// cmux's own Claude Code integration only works for LOCAL sessions: its
// claude wrapper (PATH-injected by claudeLaunchScript inside cmux panes)
// installs hooks that call the cmux CLI over the local socket. A claude
// running on a remote box over mosh+tmux has no such channel, so "needs
// input" / "finished" events died on the remote host.
//
// The bridge has two halves:
//
//   - Remote: claudeLaunchScript (bridge=true) writes a tiny hook script
//     plus a claude `--settings` overlay under ~/.cctl/ on the remote and
//     launches claude with it. Claude's Notification and Stop hooks then
//     append one JSON line per event — tagged with the tmux session name —
//     to ~/.cctl/notify.jsonl. No claude user settings are modified.
//
//   - Local: while the TUI runs, a notifyWatcher per connected remote
//     server tails that file over the server's transport and mirrors each
//     event into `cmux notify`, targeted at the session's workspace.
//
// Limitation worth knowing: events flow only while the cctl TUI is open
// (it hosts the ssh tail). The jsonl keeps accumulating regardless and
// self-rotates at 1MB, so nothing breaks when no watcher is attached.

// notifyHookScript is the hook command installed on remote servers.
// Claude invokes it with the event name as $1 and the hook payload JSON
// on stdin.
const notifyHookScript = `#!/bin/sh
# cctl: forwards claude-code hook events into ~/.cctl/notify.jsonl so a
# running cctl TUI can mirror them into cmux notifications. Autogenerated;
# edits are overwritten on the next session launch.
event="${1:-unknown}"
dir="$HOME/.cctl"
file="$dir/notify.jsonl"
mkdir -p "$dir"
if [ -f "$file" ] && [ "$(wc -c < "$file")" -gt 1048576 ]; then
  : > "$file"
fi
sess=""
if [ -n "${TMUX:-}" ]; then
  sess="$(tmux display-message -p '#S' 2>/dev/null || true)"
fi
payload="$(head -c 8192 2>/dev/null | tr -d '\n\r')"
[ -n "$payload" ] || payload=null
printf '{"ts":%s,"event":"%s","session":"%s","payload":%s}\n' \
  "$(date +%s)" "$event" "$sess" "$payload" >> "$file"
`

// notifyHookSettings is the claude --settings overlay wiring the
// Notification (needs input / permission) and Stop (finished responding)
// hooks to the script above. Hooks from --settings merge with the user's
// own settings, so nothing of theirs is replaced.
const notifyHookSettings = `{
  "hooks": {
    "Notification": [{"hooks": [{"type": "command", "command": "\"$HOME/.cctl/cmux-claude-hook.sh\" Notification"}]}],
    "Stop": [{"hooks": [{"type": "command", "command": "\"$HOME/.cctl/cmux-claude-hook.sh\" Stop"}]}]
  }
}
`

// notifyBridgeEnsureBlock returns the shell fragment claudeLaunchScript
// embeds (remote sessions only) to materialize the hook script + settings
// overlay before launching claude. Idempotent: plain overwrites.
func notifyBridgeEnsureBlock() string {
	return `mkdir -p "$HOME/.cctl"
cat > "$HOME/.cctl/cmux-claude-hook.sh" <<'CCTL_NOTIFY_HOOK'
` + notifyHookScript + `CCTL_NOTIFY_HOOK
chmod +x "$HOME/.cctl/cmux-claude-hook.sh"
cat > "$HOME/.cctl/claude-cmux-hooks.json" <<'CCTL_NOTIFY_CFG'
` + notifyHookSettings + `CCTL_NOTIFY_CFG`
}

// notifyBridgeSettingsFlag is appended (unquoted, so $HOME expands on the
// remote) to the claude invocation when the bridge is active.
const notifyBridgeSettingsFlag = ` --settings "$HOME/.cctl/claude-cmux-hooks.json"`

// ---- local side: per-server watcher -----------------------------------------

// notifyEvent is one line of ~/.cctl/notify.jsonl.
type notifyEvent struct {
	TS      int64           `json:"ts"`
	Event   string          `json:"event"`
	Session string          `json:"session"`
	Payload json.RawMessage `json:"payload"`
}

// notifyPayload is the subset of claude's hook input we surface.
type notifyPayload struct {
	Message string `json:"message"`
}

// notifyWatcher tails one remote server's notify.jsonl and posts cmux
// notifications. Lives for the duration of one transport connection;
// probedMsg restarts dead watchers on reconnect.
type notifyWatcher struct {
	server string
	stop   func()
	// replayStatus (beta) re-fires each remote claude hook event locally as
	// `cmux hooks claude <event>` against the session's surface, so cmux shows
	// native live status for remote sessions. When false, the watcher just
	// posts a cmux notification per event (the original behavior).
	replayStatus bool

	mu   sync.Mutex
	dead bool
	// lastPosted throttles per-session notification bursts (a Stop fires
	// after every claude turn).
	lastPosted map[string]time.Time
}

func (w *notifyWatcher) isDead() bool {
	w.mu.Lock()
	defer w.mu.Unlock()
	return w.dead
}

// newNotifyWatcher is the factory ensureNotifyWatcher goes through —
// a seam so unit tests that drive probedMsg don't spawn real ssh
// processes toward fake hosts.
var newNotifyWatcher = startNotifyWatcher

// startNotifyWatcher launches the ssh tail + scanner goroutine. Returns
// immediately; the watcher marks itself dead when the transport drops.
func startNotifyWatcher(serverName string, srv Server, replayStatus bool) *notifyWatcher {
	w := &notifyWatcher{server: serverName, replayStatus: replayStatus, lastPosted: map[string]time.Time{}}
	remote := `mkdir -p "$HOME/.cctl"; touch "$HOME/.cctl/notify.jsonl"; exec tail -n 0 -F "$HOME/.cctl/notify.jsonl"`
	c := remoteCmd(srv, remote)
	stdout, err := c.StdoutPipe()
	if err != nil {
		log().Warn("notify-watcher-pipe-fail", "server", serverName, "err", err.Error())
		w.dead = true
		return w
	}
	if err := c.Start(); err != nil {
		log().Warn("notify-watcher-start-fail", "server", serverName, "err", err.Error())
		w.dead = true
		return w
	}
	w.stop = func() {
		if c.Process != nil {
			_ = c.Process.Kill()
		}
	}
	log().Info("notify-watcher-start", "server", serverName)
	go func() {
		scanner := bufio.NewScanner(stdout)
		scanner.Buffer(make([]byte, 0, 64*1024), 64*1024)
		for scanner.Scan() {
			w.handleLine(scanner.Text())
		}
		_ = c.Wait()
		w.mu.Lock()
		w.dead = true
		w.mu.Unlock()
		log().Info("notify-watcher-stop", "server", serverName, "scan_err", errString(scanner.Err()))
	}()
	return w
}

// handleLine processes one notify.jsonl line. In beta replay mode it re-fires
// the event into cmux's native status for the session's surface; otherwise it
// posts a throttled cmux notification (the original behavior).
func (w *notifyWatcher) handleLine(line string) {
	if w.replayStatus && replayClaudeStatus(line) {
		return
	}
	title, body, wsTitle, sessKey, ok := parseNotifyLine(line)
	if !ok {
		return
	}
	w.mu.Lock()
	last := w.lastPosted[sessKey]
	if time.Since(last) < 3*time.Second {
		w.mu.Unlock()
		return
	}
	w.lastPosted[sessKey] = time.Now()
	w.mu.Unlock()
	log().Debug("notify-bridge-event", "server", w.server, "session", sessKey, "title", title)
	notifyCmuxSafeTitle(title, body, wsTitle)
}

// claudeHookSubcommand maps a captured claude hook event name to the
// `cmux hooks claude <subcommand>` cmux uses internally. Empty = no mapping
// (skip). Mirrors the events in cmux's own claude wrapper HOOKS_JSON.
func claudeHookSubcommand(event string) string {
	switch event {
	case "Notification":
		return "notification"
	case "Stop":
		return "stop"
	case "SessionStart":
		return "session-start"
	case "SessionEnd":
		return "session-end"
	case "UserPromptSubmit":
		return "prompt-submit"
	case "PreToolUse":
		return "pre-tool-use"
	}
	return ""
}

// replayClaudeStatus re-fires a remote claude hook event into cmux's native
// status: it finds the session's cmux surface and runs `cmux hooks claude
// <event>` locally with the claude payload on stdin and CMUX_SURFACE_ID /
// CMUX_WORKSPACE_ID pointed at that surface — exactly what cmux's own wrapper
// would do, but for a session whose claude runs on a remote host. Returns true
// when it handled the line (so the caller skips the plain notification).
func replayClaudeStatus(line string) bool {
	line = strings.TrimSpace(line)
	if line == "" {
		return false
	}
	var ev notifyEvent
	if json.Unmarshal([]byte(line), &ev) != nil {
		return false
	}
	repo, wt, sess, ok := parseTmuxName(ev.Session)
	if !ok {
		return false
	}
	sub := claudeHookSubcommand(ev.Event)
	if sub == "" {
		return false
	}
	cli := cmuxCLIPath()
	if cli == "" {
		return false
	}
	wsID, surfaceID, found := cmuxSurfaceForSafeSession(cli, repo+"/"+wt+"/"+sess)
	if !found || surfaceID == "" {
		log().Debug("cmux-hook-replay-no-surface", "session", ev.Session)
		return false // let the caller fall back to a notification
	}
	c := cmuxCmd(cli, "hooks", "claude", sub)
	c.Env = cmuxHookEnv(c.Env, wsID, surfaceID)
	if len(ev.Payload) > 0 {
		c.Stdin = bytes.NewReader(ev.Payload)
	}
	if out, err := c.CombinedOutput(); err != nil {
		log().Debug("cmux-hook-replay-fail", "event", ev.Event, "sub", sub,
			"ws", wsID, "err", err.Error(), "out", strings.TrimSpace(string(out)))
		return false
	}
	log().Info("cmux-hook-replay", "event", ev.Event, "sub", sub, "ws", wsID, "surface", surfaceID)
	return true
}

// cmuxSurfaceForSafeSession finds the cmux workspace + first surface whose
// (sanitized) name matches a "repo/worktree/session" key. cctl names one
// workspace per session, so the first surface is the session's tab.
func cmuxSurfaceForSafeSession(cli, safeName string) (wsID, surfaceID string, ok bool) {
	for _, w := range listCmuxWorkspaces(cli) {
		if tmuxSafeName(w.name) != safeName {
			continue
		}
		surfaces := listCmuxSurfaces(cli, w.id)
		if len(surfaces) == 0 {
			return w.id, "", true
		}
		return w.id, surfaces[0].id, true
	}
	return "", "", false
}

// cmuxHookEnv returns env with CMUX_WORKSPACE_ID / CMUX_SURFACE_ID set to the
// target surface (replacing cctl's own values so the replayed hook updates the
// right session, not the control pane). The local CMUX_SOCKET_PATH is kept.
func cmuxHookEnv(base []string, wsID, surfaceID string) []string {
	out := make([]string, 0, len(base)+2)
	for _, kv := range base {
		if strings.HasPrefix(kv, "CMUX_WORKSPACE_ID=") || strings.HasPrefix(kv, "CMUX_SURFACE_ID=") {
			continue
		}
		out = append(out, kv)
	}
	return append(out, "CMUX_WORKSPACE_ID="+wsID, "CMUX_SURFACE_ID="+surfaceID)
}

// parseNotifyLine turns a notify.jsonl line into notification content.
// Returns ok=false for anything malformed or for events on non-cctl
// sessions. wsTitle is built from the tmux-sanitized name parts — the
// caller matches it against workspace titles sanitized the same way.
func parseNotifyLine(line string) (title, body, wsTitle, sessKey string, ok bool) {
	line = strings.TrimSpace(line)
	if line == "" {
		return "", "", "", "", false
	}
	var ev notifyEvent
	if err := json.Unmarshal([]byte(line), &ev); err != nil {
		log().Debug("notify-bridge-parse-fail", "err", err.Error())
		return "", "", "", "", false
	}
	repo, wt, sess, named := parseTmuxName(ev.Session)
	if !named {
		return "", "", "", "", false
	}
	label := fmt.Sprintf("%s/%s/%s", repo, wt, sess)
	var p notifyPayload
	_ = json.Unmarshal(ev.Payload, &p)
	switch ev.Event {
	case "Notification":
		title = "claude needs attention — " + label
		body = p.Message
	case "Stop":
		title = "claude finished — " + label
	default:
		title = "claude " + ev.Event + " — " + label
		body = p.Message
	}
	return title, body, repo + "/" + wt, ev.Session + "/" + ev.Event, true
}

// notifyCmuxSafeTitle is notifyCmux with tmux-sanitization-tolerant
// workspace matching: the event carries sanitized name parts
// ("rxtx_dev/main") while workspace titles use real names
// ("rxtx.dev/main"), so titles are compared through tmuxSafeName.
func notifyCmuxSafeTitle(title, body, safeWsTitle string) {
	cli := cmuxCLIPath()
	if cli == "" {
		return
	}
	wsTitle := ""
	if safeWsTitle != "" {
		if name, ok := findCmuxWorkspaceNameBySafeTitle(cli, safeWsTitle); ok {
			wsTitle = name
		}
	}
	notifyCmux(title, body, wsTitle)
}
